language: php

services:
  - mysql

cache:
 directories:
  - $HOME/.composer/cache
  - .php_cs
jobs:
 include:
  - stage: test
    php: 7.2
    env: PREFER_LOWEST=""
    before_script:
     - &composerupdate
        composer update --prefer-dist $PREFER_LOWEST
    script:
     - &phpunit
        "./vendor/bin/phpunit"
     - composer phpstan
    after_script:
     - ./vendor/bin/coveralls -v
  - stage: test
    php: 7.2
    env: PREFER_LOWEST="--prefer-lowest"
    before_script:
     - *composerupdate
    script:
     - *phpunit
  - stage: test
    php: 7.1
    env: PREFER_LOWEST=""
    before_script:
     - *composerupdate
    script:
     - *phpunit
  - stage: test
    php: 7.3
    env: PREFER_LOWEST=""
    before_script:
      - *composerupdate
    script:
      - *phpunit
  - stage: test
    php: 7.4
    env: PREFER_LOWEST=""
    before_script:
      - *composerupdate
    script:
      - *phpunit
